#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@k3screenctrl[-1]
	add ucitrack k3screenctrl
	set ucitrack.@k3screenctrl[-1].init=k3screenctrl
	commit ucitrack
EOF

general=$(uci -q get k3screenctrl.@general[-1])

if [ -z "$general" ]; then
	uci -q add k3screenctrl general
fi

rm -rf /tmp/luci*

exit 0
